### ISSUE TITLE
gem doesn't exist

### ISSUE THREAD

**Issue by beno** [kematzy/roda-i18n#1]
Can't load this gem from rubygems 

``` ruby
gem 'roda-i18n'
 # => Could not find gem 'roda-i18n (>= 0) ruby' in any of the gem sources listed in your Gemfile or installed on this machine.
```

or github

``` ruby
gem 'roda-i18n', github: 'kematzy/roda-i18n'
# => Could not find gem 'roda-i18n (>= 0) ruby' in git://github.com/kematzy/roda-i18n.git (at master).
#    Source does not contain any versions of 'roda-i18n (>= 0) ruby'
```

**Comment by kematzy** [comment]
Hi Beno,

The gem was never pushed as I had to clean-up the code a bit, but never got
around to updating the repo and push the gem.

It's on my ToDo list ;-)

**Comment by beno** [comment]
ok thanks

**Comment by beno** [comment]
By the way, is there any specific reason you used R18n istead of plain old I18n for this? R18n is incredibly confusing to me (default_places wtf?)

**Comment by kematzy** [comment]
Hi Beno,

I guess I chose R18n many years ago because it was more flexible and less "Railsy" and was easy to integrate with Sinatra.

This Roda plugin is really just a conversion of a Sinatra plugin that I used. 

Give R18n a chance and I'm sure you'll like it.
